using Ato.Copilot.Core.Models.Compliance;

namespace Ato.Copilot.Core.Dtos.Dashboard;

/// <summary>
/// Request to create a new Security Assessment Report.
/// </summary>
public record CreateSarRequest
{
    public string Title { get; init; } = string.Empty;
    public string? SapId { get; init; }
}

/// <summary>
/// SAR response DTO with summary metrics and section listing.
/// </summary>
public record SarResponse
{
    public string SarId { get; init; } = string.Empty;
    public string SystemId { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public string Status { get; init; } = string.Empty;
    public int TotalControlsAssessed { get; init; }
    public int TotalControlsPending { get; init; }
    public int SatisfiedCount { get; init; }
    public int NotSatisfiedCount { get; init; }
    public required IReadOnlyList<SarSectionSummaryDto> Sections { get; init; }
    public string CreatedBy { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
    public string? ModifiedBy { get; init; }
    public DateTime? ModifiedAt { get; init; }
    public string? ReviewedBy { get; init; }
    public DateTime? ReviewedAt { get; init; }
    public string? ApprovedBy { get; init; }
    public DateTime? ApprovedAt { get; init; }
}

/// <summary>
/// Section summary within SAR response (without full content).
/// </summary>
public record SarSectionSummaryDto
{
    public string SectionType { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }
    public bool HasContent { get; init; }
}

/// <summary>
/// Full section response including content for editing.
/// </summary>
public record SarSectionResponse
{
    public string SectionType { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public string Content { get; init; } = string.Empty;
    public bool IsAutoGenerated { get; init; }
    public string? ModifiedBy { get; init; }
    public DateTime? ModifiedAt { get; init; }
}

/// <summary>
/// Request to edit a SAR narrative section.
/// </summary>
public record EditSarSectionRequest
{
    public string Content { get; init; } = string.Empty;
}

/// <summary>
/// Request to review (approve or request revision of) a SAR.
/// </summary>
public record ReviewSarRequest
{
    public string Decision { get; init; } = string.Empty;
    public string? Comments { get; init; }
}
