using Ato.Copilot.Core.Dtos.Dashboard;
using Ato.Copilot.Core.Interfaces.Compliance;
using Ato.Copilot.Core.Models.Compliance;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Ato.Copilot.Mcp.Endpoints;

/// <summary>
/// Dashboard API endpoints for SAR lifecycle and authorization package management.
/// </summary>
public static class PackageEndpoints
{
    public static IEndpointRouteBuilder MapPackageEndpoints(this IEndpointRouteBuilder app)
    {
        var systems = app.MapGroup("/api/v1/systems/{systemId}")
            .WithTags("AuthorizationPackage");

        // ─── SAR Endpoints ─────────────────────────────────────────────────

        systems.MapPost("/sar", async (
                string systemId,
                CreateSarRequest request,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                try
                {
                    var sar = await service.CreateSarAsync(systemId, request, "mcp-user", ct);
                    return Results.Created($"/api/v1/systems/{systemId}/sar/{sar.Id}", MapSarResponse(sar));
                }
                catch (InvalidOperationException ex)
                {
                    return Results.BadRequest(new ErrorResponse { Error = ex.Message, ErrorCode = "SAR_CREATION_FAILED" });
                }
            })
            .WithName("CreateSar");

        systems.MapGet("/sar", async (
                string systemId,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                var sar = await service.GetSarForSystemAsync(systemId, ct);
                if (sar == null)
                    return Results.NotFound();
                return Results.Ok(MapSarResponse(sar));
            })
            .WithName("GetLatestSar");

        systems.MapGet("/sar/{sarId}", async (
                string systemId,
                string sarId,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                var sar = await service.GetSarAsync(sarId, ct);
                if (sar == null || sar.RegisteredSystemId != systemId)
                    return Results.NotFound();
                return Results.Ok(MapSarResponse(sar));
            })
            .WithName("GetSar");

        systems.MapPut("/sar/{sarId}/sections/{sectionType}", async (
                string systemId,
                string sarId,
                string sectionType,
                EditSarSectionRequest request,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                if (!Enum.TryParse<SarSectionType>(sectionType, true, out var parsedType))
                    return Results.BadRequest(new ErrorResponse { Error = $"Invalid section type: {sectionType}", ErrorCode = "INVALID_SECTION_TYPE" });

                try
                {
                    var section = await service.EditSectionAsync(sarId, parsedType, request, "mcp-user", ct);
                    return Results.Ok(new SarSectionResponse
                    {
                        SectionType = section.SectionType.ToString(),
                        Title = section.Title,
                        Content = section.Content ?? "",
                        IsAutoGenerated = section.IsAutoGenerated,
                        ModifiedBy = section.ModifiedBy,
                        ModifiedAt = section.ModifiedAt
                    });
                }
                catch (InvalidOperationException ex)
                {
                    return Results.Conflict(new ErrorResponse { Error = ex.Message, ErrorCode = "EDIT_FAILED" });
                }
            })
            .WithName("EditSarSection");

        systems.MapPost("/sar/{sarId}/submit", async (
                string systemId,
                string sarId,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                try
                {
                    var sar = await service.SubmitForReviewAsync(sarId, "mcp-user", ct);
                    return Results.Ok(MapSarResponse(sar));
                }
                catch (InvalidOperationException ex)
                {
                    return Results.Conflict(new ErrorResponse { Error = ex.Message, ErrorCode = "SUBMIT_FAILED" });
                }
            })
            .WithName("SubmitSarForReview");

        systems.MapPost("/sar/{sarId}/review", async (
                string systemId,
                string sarId,
                ReviewSarRequest request,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                try
                {
                    var sar = await service.ReviewSarAsync(sarId, request, "mcp-user", ct);
                    return Results.Ok(MapSarResponse(sar));
                }
                catch (InvalidOperationException ex)
                {
                    return Results.Conflict(new ErrorResponse { Error = ex.Message, ErrorCode = "REVIEW_FAILED" });
                }
            })
            .WithName("ReviewSar");

        systems.MapGet("/sar/{sarId}/export", async (
                string systemId,
                string sarId,
                ISecurityAssessmentReportService service,
                CancellationToken ct) =>
            {
                try
                {
                    var stream = await service.ExportToWordAsync(sarId, ct);
                    return Results.File(stream,
                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        $"security-assessment-report-{sarId[..8]}.docx");
                }
                catch (InvalidOperationException)
                {
                    return Results.NotFound();
                }
            })
            .WithName("ExportSarWord");

        // ─── SAP Endpoints ─────────────────────────────────────────────────

        systems.MapPost("/sap", async (
                string systemId,
                ISapService service,
                CancellationToken ct) =>
            {
                try
                {
                    var input = new SapGenerationInput(SystemId: systemId);
                    var sap = await service.GenerateSapAsync(input, "dashboard-user", ct);
                    return Results.Created($"/api/v1/systems/{systemId}/sap/{sap.SapId}", MapSapResponse(sap));
                }
                catch (InvalidOperationException ex)
                {
                    return Results.BadRequest(new ErrorResponse { Error = ex.Message, ErrorCode = "SAP_GENERATION_FAILED" });
                }
            })
            .WithName("GenerateSap");

        systems.MapGet("/sap", async (
                string systemId,
                ISapService service,
                CancellationToken ct) =>
            {
                var sap = await service.GetSapStatusAsync(systemId, ct);
                if (sap == null)
                    return Results.NotFound();
                return Results.Ok(MapSapResponse(sap));
            })
            .WithName("GetLatestSap");

        systems.MapPost("/sap/{sapId}/finalize", async (
                string systemId,
                string sapId,
                ISapService service,
                CancellationToken ct) =>
            {
                try
                {
                    var sap = await service.FinalizeSapAsync(sapId, "dashboard-user", ct);
                    return Results.Ok(MapSapResponse(sap));
                }
                catch (InvalidOperationException ex)
                {
                    return Results.Conflict(new ErrorResponse { Error = ex.Message, ErrorCode = "SAP_FINALIZE_FAILED" });
                }
            })
            .WithName("FinalizeSap");

        // ─── OSCAL Schema Validation Endpoints ─────────────────────────────

        systems.MapPost("/exports/validate-oscal", async (
                string systemId,
                ValidateOscalRequest request,
                IOscalSchemaValidationService service,
                CancellationToken ct) =>
            {
                var result = await service.ValidateForSystemAsync(systemId, request.Model, ct);
                return Results.Ok(new
                {
                    isValid = result.IsValid,
                    modelType = result.ModelType,
                    schemaVersion = result.SchemaVersion,
                    violationCount = result.Violations.Count,
                    violations = result.Violations.Select(v => new
                    {
                        jsonPath = v.JsonPath,
                        message = v.Message,
                        expectedFormat = v.ExpectedFormat,
                        actualValue = v.ActualValue
                    })
                });
            })
            .WithName("ValidateOscalSchema");

        // ─── Standalone OSCAL Export Endpoints ──────────────────────────────

        systems.MapGet("/exports/oscal-poam", async (
                string systemId,
                IEmassExportService emassService,
                CancellationToken ct) =>
            {
                var json = await emassService.ExportOscalAsync(systemId, OscalModelType.Poam, ct);
                return Results.Text(json, "application/json");
            })
            .WithName("ExportOscalPoam");

        systems.MapGet("/exports/oscal-assessment-results", async (
                string systemId,
                IEmassExportService emassService,
                CancellationToken ct) =>
            {
                var json = await emassService.ExportOscalAsync(systemId, OscalModelType.AssessmentResults, ct);
                return Results.Text(json, "application/json");
            })
            .WithName("ExportOscalAssessmentResults");

        systems.MapGet("/exports/oscal-sap", async (
                string systemId,
                IOscalSapExportService sapService,
                CancellationToken ct) =>
            {
                var json = await sapService.ExportAsync(systemId, ct);
                return Results.Text(json, "application/json");
            })
            .WithName("ExportOscalSap");

        // ─── Package Validation Endpoints ───────────────────────────────────

        systems.MapPost("/packages/validate", async (
                string systemId,
                IPackageValidationService service,
                CancellationToken ct) =>
            {
                var result = await service.ValidateAsync(systemId, "dashboard-user", ct);
                return Results.Ok(new
                {
                    isValid = result.IsValid,
                    errorCount = result.ErrorCount,
                    warningCount = result.WarningCount,
                    validatedAt = result.ValidatedAt,
                    findings = result.Findings.Select(f => new
                    {
                        severity = f.Severity.ToString().ToLowerInvariant(),
                        category = f.Category,
                        artifactType = f.ArtifactType,
                        description = f.Description,
                        remediation = f.Remediation
                    })
                });
            })
            .WithName("ValidatePackage");

        // ─── Package Generation & Management Endpoints ──────────────────────

        systems.MapPost("/packages", async (
                string systemId,
                GeneratePackageRequest request,
                IAuthorizationPackageService service,
                CancellationToken ct) =>
            {
                try
                {
                    var package = await service.EnqueuePackageAsync(systemId, request.EvidenceMode, "dashboard-user", ct);
                    return Results.Accepted(
                        $"/api/v1/systems/{systemId}/packages/{package.Id}",
                        new
                        {
                            packageId = package.Id,
                            status = package.Status.ToString(),
                            message = "Package generation has been queued."
                        });
                }
                catch (InvalidOperationException ex)
                {
                    return Results.BadRequest(new ErrorResponse { Error = ex.Message, ErrorCode = "READINESS_CHECK_FAILED" });
                }
            })
            .WithName("GeneratePackage");

        systems.MapGet("/packages", async (
                string systemId,
                int? limit,
                int? offset,
                bool? includeFailed,
                IAuthorizationPackageService service,
                CancellationToken ct) =>
            {
                var result = await service.ListPackagesAsync(
                    systemId,
                    limit ?? 20,
                    offset ?? 0,
                    includeFailed ?? false,
                    ct);
                return Results.Ok(result);
            })
            .WithName("ListPackages");

        systems.MapGet("/packages/{packageId}", async (
                string systemId,
                string packageId,
                IAuthorizationPackageService service,
                CancellationToken ct) =>
            {
                var package = await service.GetPackageAsync(packageId, ct);
                if (package == null || package.RegisteredSystemId != systemId)
                    return Results.NotFound();

                return Results.Ok(new PackageDetailResponse
                {
                    PackageId = package.Id,
                    SystemId = package.RegisteredSystemId,
                    Status = package.Status.ToString(),
                    EvidenceMode = package.EvidenceMode.ToString(),
                    Artifacts = (package.Artifacts ?? []).Select(a => new PackageArtifactDto
                    {
                        ArtifactId = a.Id,
                        Type = a.ArtifactType.ToString(),
                        Format = a.Format ?? "",
                        FileName = a.FileName ?? "",
                        FileSize = a.FileSize,
                        OscalVersion = a.OscalVersion,
                        SchemaValid = a.SchemaValid,
                        GeneratedAt = a.GeneratedAt
                    }).ToList(),
                    Validation = package.ValidationResult != null
                        ? new PackageValidationDto
                        {
                            IsValid = package.ValidationResult.IsValid,
                            ErrorCount = package.ValidationResult.ErrorCount,
                            WarningCount = package.ValidationResult.WarningCount,
                            Findings = (package.ValidationResult.Findings ?? []).Select(f => new ValidationFindingDto
                            {
                                Severity = f.Severity.ToString().ToLowerInvariant(),
                                Category = f.Category ?? "",
                                ArtifactType = f.ArtifactType,
                                Description = f.Description ?? "",
                                Remediation = f.Remediation
                            }).ToList()
                        }
                        : null,
                    FileSize = package.FileSize,
                    FailureReason = package.FailureReason,
                    FailedArtifactType = package.FailedArtifactType?.ToString(),
                    GeneratedBy = package.GeneratedBy ?? "",
                    GeneratedAt = package.GeneratedAt,
                    CompletedAt = package.CompletedAt,
                    ExpiresAt = package.ExpiresAt
                });
            })
            .WithName("GetPackage");

        systems.MapGet("/packages/{packageId}/download", async (
                string systemId,
                string packageId,
                IAuthorizationPackageService service,
                CancellationToken ct) =>
            {
                var package = await service.GetPackageAsync(packageId, ct);
                if (package == null || package.RegisteredSystemId != systemId)
                    return Results.NotFound();

                var stream = await service.DownloadPackageAsync(packageId, ct);
                if (stream == null)
                    return Results.NotFound(new ErrorResponse
                    {
                        Error = "Package file not available. It may have expired or generation may still be in progress.",
                        ErrorCode = "DOWNLOAD_NOT_AVAILABLE"
                    });

                return Results.File(stream,
                    "application/zip",
                    $"authorization-package-{packageId[..8]}.zip");
            })
            .WithName("DownloadPackage");

        return app;
    }

    private static SarResponse MapSarResponse(SecurityAssessmentReport sar)
    {
        return new SarResponse
        {
            SarId = sar.Id,
            SystemId = sar.RegisteredSystemId,
            Title = sar.Title,
            Status = sar.Status.ToString(),
            TotalControlsAssessed = sar.TotalControlsAssessed,
            TotalControlsPending = sar.TotalControlsPending,
            SatisfiedCount = sar.SatisfiedCount,
            NotSatisfiedCount = sar.NotSatisfiedCount,
            Sections = (sar.Sections ?? []).Select(s => new SarSectionSummaryDto
            {
                SectionType = s.SectionType.ToString(),
                Title = s.Title,
                IsAutoGenerated = s.IsAutoGenerated,
                HasContent = !string.IsNullOrWhiteSpace(s.Content)
            }).ToList(),
            CreatedBy = sar.CreatedBy,
            CreatedAt = sar.CreatedAt,
            ModifiedBy = sar.ModifiedBy,
            ModifiedAt = sar.ModifiedAt,
            ReviewedBy = sar.ReviewedBy,
            ReviewedAt = sar.ReviewedAt,
            ApprovedBy = sar.ApprovedBy,
            ApprovedAt = sar.ApprovedAt
        };
    }

    private static object MapSapResponse(SapDocument sap)
    {
        return new
        {
            sapId = sap.SapId,
            systemId = sap.SystemId,
            assessmentId = sap.AssessmentId,
            title = sap.Title,
            status = sap.Status,
            format = sap.Format,
            baselineLevel = sap.BaselineLevel,
            contentHash = sap.ContentHash,
            totalControls = sap.TotalControls,
            customerControls = sap.CustomerControls,
            inheritedControls = sap.InheritedControls,
            sharedControls = sap.SharedControls,
            stigBenchmarkCount = sap.StigBenchmarkCount,
            controlsWithObjectives = sap.ControlsWithObjectives,
            evidenceGaps = sap.EvidenceGaps,
            familySummaries = sap.FamilySummaries.Select(f => new
            {
                family = f.Family,
                controlCount = f.ControlCount,
                customerCount = f.CustomerCount,
                inheritedCount = f.InheritedCount,
                methods = f.Methods
            }),
            generatedAt = sap.GeneratedAt,
            finalizedAt = sap.FinalizedAt,
            warnings = sap.Warnings
        };
    }
}
