import axios from 'axios';
import { attachAuthInterceptor } from '../features/auth/interceptors';
import { getMsalInstance, DEFAULT_API_SCOPES } from '../features/auth/msalInstance';

// ─── V1 API Client ──────────────────────────────────────────────────────────

const v1Client = axios.create({
  baseURL: '/api/v1',
  headers: { 'Content-Type': 'application/json' },
});

// Feature 051 T053: MSAL bearer injection (silent renewal + 401 retry).
attachAuthInterceptor(v1Client, getMsalInstance, DEFAULT_API_SCOPES);

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface CreateSarRequest {
  title: string;
  sapId?: string;
}

export interface SarSectionSummary {
  sectionType: string;
  title: string;
  isAutoGenerated: boolean;
  hasContent: boolean;
}

export interface SarResponse {
  sarId: string;
  systemId: string;
  title: string;
  status: string;
  totalControlsAssessed: number;
  totalControlsPending: number;
  satisfiedCount: number;
  notSatisfiedCount: number;
  sections: SarSectionSummary[];
  createdBy: string;
  createdAt: string;
  modifiedBy?: string;
  modifiedAt?: string;
  reviewedBy?: string;
  reviewedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
}

export interface SarSectionResponse {
  sectionType: string;
  title: string;
  content: string;
  isAutoGenerated: boolean;
  modifiedBy?: string;
  modifiedAt?: string;
}

export interface ReviewSarRequest {
  decision: 'approve' | 'request_revision';
  comments?: string;
}

// ─── API Functions ────────────────────────────────────────────────────────────

const BASE = '/systems';

export async function createSar(systemId: string, request: CreateSarRequest) {
  const { data } = await v1Client.post<SarResponse>(`${BASE}/${systemId}/sar`, request);
  return data;
}

export async function getLatestSar(systemId: string) {
  const { data } = await v1Client.get<SarResponse>(`${BASE}/${systemId}/sar`);
  return data;
}

export async function getSar(systemId: string, sarId: string) {
  const { data } = await v1Client.get<SarResponse>(`${BASE}/${systemId}/sar/${sarId}`);
  return data;
}

export async function editSarSection(systemId: string, sarId: string, sectionType: string, content: string) {
  const { data } = await v1Client.put<SarSectionResponse>(
    `${BASE}/${systemId}/sar/${sarId}/sections/${sectionType}`,
    { content }
  );
  return data;
}

export async function submitSarForReview(systemId: string, sarId: string) {
  const { data } = await v1Client.post<SarResponse>(`${BASE}/${systemId}/sar/${sarId}/submit`);
  return data;
}

export async function reviewSar(systemId: string, sarId: string, request: ReviewSarRequest) {
  const { data } = await v1Client.post<SarResponse>(`${BASE}/${systemId}/sar/${sarId}/review`, request);
  return data;
}

export async function exportSarWord(systemId: string, sarId: string) {
  const response = await v1Client.get(`${BASE}/${systemId}/sar/${sarId}/export`, {
    responseType: 'blob'
  });
  return response.data as Blob;
}
