using Ato.Copilot.Agents.Compliance.Services;
using Ato.Copilot.Core.Data.Context;
using Ato.Copilot.Core.Models.Compliance;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace Ato.Copilot.Tests.Unit.Services;

/// <summary>
/// Unit tests for SspService section authoring methods (Feature 022).
/// Covers WriteSspSectionAsync, ReviewSspSectionAsync, GetSspCompletenessAsync.
/// </summary>
public class SspServiceSectionTests : IDisposable
{
    private readonly ServiceProvider _serviceProvider;
    private readonly AtoCopilotContext _db;
    private readonly SspService _service;

    public SspServiceSectionTests()
    {
        var dbName = $"SspServiceSection_{Guid.NewGuid()}";
        var services = new ServiceCollection();
        services.AddDbContext<AtoCopilotContext>(o => o.UseInMemoryDatabase(dbName));
        services.AddLogging();
        _serviceProvider = services.BuildServiceProvider();
        _db = _serviceProvider.GetRequiredService<AtoCopilotContext>();
        _service = new SspService(
            _serviceProvider.GetRequiredService<IServiceScopeFactory>(),
            Mock.Of<ILogger<SspService>>());
    }

    public void Dispose() => _serviceProvider.Dispose();

    private async Task<RegisteredSystem> SeedSystemAsync(string? name = null)
    {
        var system = new RegisteredSystem
        {
            Id = Guid.NewGuid().ToString(),
            Name = name ?? "Test System",
            Acronym = "TST",
            Description = "A test system for unit tests",
            SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Government"
        };
        _db.RegisteredSystems.Add(system);
        await _db.SaveChangesAsync();
        _db.ChangeTracker.Clear();
        return system;
    }

    // ────────────────────────────────────────────────────────────────────────
    // WriteSspSectionAsync Tests
    // ────────────────────────────────────────────────────────────────────────

    [Fact]
    public async Task WriteSspSection_CreatesNewSection_ForAuthoredSection()
    {
        var system = await SeedSystemAsync();

        var result = await _service.WriteSspSectionAsync(
            system.Id, 5, "## Rules of Behavior\nAll users must...", "author@test.com");

        result.Should().NotBeNull();
        result.SectionNumber.Should().Be(5);
        result.SectionTitle.Should().Be("General Description / Purpose");
        result.Status.Should().Be(SspSectionStatus.Draft);
        result.Version.Should().Be(1);
        result.IsAutoGenerated.Should().BeFalse();
        result.HasManualOverride.Should().BeFalse();
        result.AuthoredBy.Should().Be("author@test.com");
        result.Content.Should().Contain("Rules of Behavior");
    }

    [Fact]
    public async Task WriteSspSection_CreatesAutoGenSection_WithoutContent()
    {
        var system = await SeedSystemAsync();

        var result = await _service.WriteSspSectionAsync(
            system.Id, 1, null, "author@test.com");

        result.Should().NotBeNull();
        result.SectionNumber.Should().Be(1);
        result.IsAutoGenerated.Should().BeTrue();
        result.HasManualOverride.Should().BeFalse();
        result.Status.Should().Be(SspSectionStatus.Draft);
        result.Version.Should().Be(1);
    }

    [Fact]
    public async Task WriteSspSection_SetsHasManualOverride_WhenAutoGenSectionHasContent()
    {
        var system = await SeedSystemAsync();

        var result = await _service.WriteSspSectionAsync(
            system.Id, 1, "Custom override content", "author@test.com");

        result.IsAutoGenerated.Should().BeTrue();
        result.HasManualOverride.Should().BeTrue();
        result.Content.Should().Be("Custom override content");
    }

    [Fact]
    public async Task WriteSspSection_IncrementsVersion_OnUpdate()
    {
        var system = await SeedSystemAsync();

        var v1 = await _service.WriteSspSectionAsync(
            system.Id, 5, "Initial content", "author@test.com");
        v1.Version.Should().Be(1);

        var v2 = await _service.WriteSspSectionAsync(
            system.Id, 5, "Updated content", "author@test.com");
        v2.Version.Should().Be(2);
        v2.Content.Should().Be("Updated content");
        v2.Status.Should().Be(SspSectionStatus.Draft);
    }

    [Fact]
    public async Task WriteSspSection_SubmitsForReview_WhenFlagSet()
    {
        var system = await SeedSystemAsync();

        var result = await _service.WriteSspSectionAsync(
            system.Id, 5, "Content for review", "author@test.com",
            submitForReview: true);

        result.Status.Should().Be(SspSectionStatus.UnderReview);
    }

    [Fact]
    public async Task WriteSspSection_ThrowsConcurrencyConflict_WhenVersionMismatch()
    {
        var system = await SeedSystemAsync();
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Initial", "author@test.com");

        var act = () => _service.WriteSspSectionAsync(
            system.Id, 5, "Update", "author@test.com", expectedVersion: 99);

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("CONCURRENCY_CONFLICT*");
    }

    [Fact]
    public async Task WriteSspSection_ThrowsInvalidSection_ForOutOfRange()
    {
        var system = await SeedSystemAsync();

        var act = () => _service.WriteSspSectionAsync(
            system.Id, 14, "Content", "author@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("INVALID_SECTION_NUMBER*");
    }

    [Fact]
    public async Task WriteSspSection_ThrowsContentRequired_ForAuthoredSectionWithoutContent()
    {
        var system = await SeedSystemAsync();

        var act = () => _service.WriteSspSectionAsync(
            system.Id, 5, null, "author@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("CONTENT_REQUIRED*");
    }

    [Fact]
    public async Task WriteSspSection_ThrowsSystemNotFound_ForInvalidId()
    {
        var act = () => _service.WriteSspSectionAsync(
            "nonexistent-id", 1, null, "author@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("SYSTEM_NOT_FOUND*");
    }

    [Fact]
    public async Task WriteSspSection_ResetsStatusToDraft_OnUpdate()
    {
        var system = await SeedSystemAsync();

        // Create and submit for review
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com", submitForReview: true);

        // Update should reset to Draft
        var result = await _service.WriteSspSectionAsync(
            system.Id, 5, "Updated content", "author@test.com");

        result.Status.Should().Be(SspSectionStatus.Draft);
        result.Version.Should().Be(2);
    }

    [Fact]
    public async Task WriteSspSection_HandlesHybridSection6()
    {
        var system = await SeedSystemAsync();

        // Section 6 is hybrid — requires content
        var act = () => _service.WriteSspSectionAsync(
            system.Id, 6, null, "author@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("CONTENT_REQUIRED*");

        // With content should succeed
        var result = await _service.WriteSspSectionAsync(
            system.Id, 6, "Security controls content", "author@test.com");

        result.Should().NotBeNull();
        result.SectionNumber.Should().Be(6);
    }

    // ────────────────────────────────────────────────────────────────────────
    // ReviewSspSectionAsync Tests
    // ────────────────────────────────────────────────────────────────────────

    [Fact]
    public async Task ReviewSspSection_ApprovesSection()
    {
        var system = await SeedSystemAsync();
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com", submitForReview: true);

        var result = await _service.ReviewSspSectionAsync(
            system.Id, 5, "approve", "reviewer@test.com");

        result.Status.Should().Be(SspSectionStatus.Approved);
        result.ReviewedBy.Should().Be("reviewer@test.com");
        result.ReviewedAt.Should().NotBeNull();
    }

    [Fact]
    public async Task ReviewSspSection_RequestsRevision_WithComments()
    {
        var system = await SeedSystemAsync();
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com", submitForReview: true);

        var result = await _service.ReviewSspSectionAsync(
            system.Id, 5, "request_revision", "reviewer@test.com", "Needs more detail");

        result.Status.Should().Be(SspSectionStatus.Draft);
        result.ReviewerComments.Should().Be("Needs more detail");
    }

    [Fact]
    public async Task ReviewSspSection_ThrowsInvalidStatus_WhenNotUnderReview()
    {
        var system = await SeedSystemAsync();
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com");

        var act = () => _service.ReviewSspSectionAsync(
            system.Id, 5, "approve", "reviewer@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("INVALID_STATUS_FOR_REVIEW*");
    }

    [Fact]
    public async Task ReviewSspSection_ThrowsCommentsRequired_ForRevisionWithoutComments()
    {
        var system = await SeedSystemAsync();
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com", submitForReview: true);

        var act = () => _service.ReviewSspSectionAsync(
            system.Id, 5, "request_revision", "reviewer@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("COMMENTS_REQUIRED*");
    }

    [Fact]
    public async Task ReviewSspSection_ThrowsSectionNotFound_WhenMissing()
    {
        var system = await SeedSystemAsync();

        var act = () => _service.ReviewSspSectionAsync(
            system.Id, 5, "approve", "reviewer@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("SECTION_NOT_FOUND*");
    }

    [Fact]
    public async Task ReviewSspSection_ThrowsInvalidDecision_ForBadInput()
    {
        var system = await SeedSystemAsync();
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com", submitForReview: true);

        var act = () => _service.ReviewSspSectionAsync(
            system.Id, 5, "reject", "reviewer@test.com");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("INVALID_DECISION*");
    }

    // ────────────────────────────────────────────────────────────────────────
    // GetSspCompletenessAsync Tests
    // ────────────────────────────────────────────────────────────────────────

    [Fact]
    public async Task GetSspCompleteness_ReturnsEmptyReport_ForNewSystem()
    {
        var system = await SeedSystemAsync();

        var report = await _service.GetSspCompletenessAsync(system.Id);

        report.Should().NotBeNull();
        report.SystemName.Should().Be("Test System");
        report.TotalSections.Should().Be(13);
        report.ApprovedCount.Should().Be(0);
        report.OverallReadinessPercent.Should().Be(0);
        report.Sections.Should().HaveCount(13);
        report.BlockingIssues.Should().NotBeEmpty();
    }

    [Fact]
    public async Task GetSspCompleteness_TracksApprovedSections()
    {
        var system = await SeedSystemAsync();

        // Write and approve section 5
        await _service.WriteSspSectionAsync(
            system.Id, 5, "Content", "author@test.com", submitForReview: true);
        await _service.ReviewSspSectionAsync(
            system.Id, 5, "approve", "reviewer@test.com");

        var report = await _service.GetSspCompletenessAsync(system.Id);

        report.ApprovedCount.Should().Be(1);
        var readiness = Math.Round(1.0 / 13.0 * 100, 0);
        report.OverallReadinessPercent.Should().BeApproximately(readiness, 1);
    }

    [Fact]
    public async Task GetSspCompleteness_IncludesSectionSummaries()
    {
        var system = await SeedSystemAsync();

        await _service.WriteSspSectionAsync(
            system.Id, 5, "Rules content here", "author@test.com");

        var report = await _service.GetSspCompletenessAsync(system.Id);

        var section5 = report.Sections.FirstOrDefault(s => s.SectionNumber == 5);
        section5.Should().NotBeNull();
        section5!.Status.Should().Be("Draft");
        section5.AuthoredBy.Should().Be("author@test.com");
        section5.WordCount.Should().BeGreaterThan(0);
        section5.Version.Should().Be(1);
    }

    [Fact]
    public async Task GetSspCompleteness_ThrowsSystemNotFound_ForInvalidId()
    {
        var act = () => _service.GetSspCompletenessAsync("nonexistent-id");

        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("SYSTEM_NOT_FOUND*");
    }

    [Fact]
    public async Task GetSspCompleteness_FullApproval_Shows100Percent()
    {
        var system = await SeedSystemAsync();

        // Write and approve all 13 sections
        for (var i = 1; i <= 13; i++)
        {
            var content = i is 5 or 6 or 8 or 12 or 13 ? $"Section {i} content" : null;
            await _service.WriteSspSectionAsync(
                system.Id, i, content, "author@test.com", submitForReview: true);
            await _service.ReviewSspSectionAsync(
                system.Id, i, "approve", "reviewer@test.com");
        }

        var report = await _service.GetSspCompletenessAsync(system.Id);

        report.ApprovedCount.Should().Be(13);
        report.OverallReadinessPercent.Should().Be(100);
        report.BlockingIssues.Should().BeEmpty();
    }

    // ─── Section Generator Tests (Feature 022 Phase 4 — T024) ───────────────

    [Fact]
    public void Section1_IncludesDitprIdAndEmassId()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "MySystem", Acronym = "MS",
            DitprId = "DITPR-12345", EmassId = "EMASS-67890",
            SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Government"
        };

        var content = SspService.GenerateSection1Content(system, []);

        content.Should().Contain("**DITPR ID**: DITPR-12345");
        content.Should().Contain("**eMASS ID**: EMASS-67890");
        content.Should().Contain("**System Name**: MySystem");
        content.Should().Contain("**Acronym**: MS");
    }

    [Fact]
    public void Section1_IncludesPersonnelTable()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov"
        };
        var roles = new List<RmfRoleAssignment>
        {
            new() { RmfRole = RmfRole.Isso, UserId = "user1", UserDisplayName = "Jane Doe",
                     RegisteredSystemId = "sys-1", AssignedAt = DateTime.UtcNow, IsActive = true }
        };

        var content = SspService.GenerateSection1Content(system, roles);

        content.Should().Contain("### Key Personnel");
        content.Should().Contain("| Isso | Jane Doe | user1 |");
    }

    [Fact]
    public void Section2_IncludesFips200Reference()
    {
        var cat = new SecurityCategorization
        {
            RegisteredSystemId = "sys-1",
            InformationTypes = new List<InformationType>
            {
                new()
                {
                    Sp80060Id = "D.1.1", Name = "Defense Ops",
                    ConfidentialityImpact = ImpactValue.Moderate,
                    IntegrityImpact = ImpactValue.Moderate,
                    AvailabilityImpact = ImpactValue.Moderate
                }
            }
        };

        var content = SspService.GenerateSection2Content(cat);

        content.Should().Contain("FIPS 200 Reference");
        content.Should().Contain("Moderate");
        content.Should().Contain("| D.1.1 | Defense Ops |");
    }

    [Fact]
    public void Section2_NoCategorization_ReturnsPlaceholder()
    {
        var content = SspService.GenerateSection2Content(null);

        content.Should().Contain("not been performed");
    }

    [Fact]
    public void Section3_GeneratesRoleDescriptions()
    {
        var roles = new List<RmfRoleAssignment>
        {
            new() { RmfRole = RmfRole.SystemOwner, UserId = "so1", UserDisplayName = "John Smith",
                     RegisteredSystemId = "sys-1", AssignedAt = new DateTime(2024, 1, 15), IsActive = true },
            new() { RmfRole = RmfRole.AuthorizingOfficial, UserId = "ao1", UserDisplayName = "Jane Doe",
                     RegisteredSystemId = "sys-1", AssignedAt = new DateTime(2024, 2, 1), IsActive = true }
        };

        var content = SspService.GenerateSection3Content(roles);

        content.Should().Contain("### SystemOwner");
        content.Should().Contain("### AuthorizingOfficial");
        content.Should().Contain("2024-01-15");
        content.Should().Contain("**Name**: John Smith");
        content.Should().Contain("**Responsibilities**: Responsible for the overall procurement");
        content.Should().Contain("**Responsibilities**: Senior official with the authority");
    }

    [Fact]
    public void Section3_NoRoles_ReturnsPlaceholder()
    {
        var content = SspService.GenerateSection3Content([]);

        content.Should().Contain("No personnel assignments");
    }

    [Fact]
    public void Section4_IncludesOperationalStatusAndDates()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.Enclave,
            MissionCriticality = MissionCriticality.MissionCritical,
            HostingEnvironment = "Azure Gov",
            OperationalStatus = OperationalStatus.Operational,
            OperationalDate = new DateTime(2023, 6, 1),
            DisposalDate = new DateTime(2028, 12, 31)
        };

        var content = SspService.GenerateSection4Content(system);

        content.Should().Contain("Enclave / General Support System");
        content.Should().Contain("**Operational Status**: Operational");
        content.Should().Contain("**Operational Date**: 2023-06-01");
        content.Should().Contain("**Planned Disposal Date**: 2028-12-31");
    }

    [Fact]
    public void Section5_AuthoredContent_ReturnsContent()
    {
        var section = new SspSection
        {
            SectionNumber = 5, Content = "This system provides compliance automation.",
            RegisteredSystemId = "sys-1", SectionTitle = "General Description / Purpose"
        };
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov", Description = "Fallback description"
        };

        var content = SspService.GenerateSection5Content(section, system);

        content.Should().Be("This system provides compliance automation.");
    }

    [Fact]
    public void Section5_NoSection_FallsBackToDescription()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov", Description = "System description fallback"
        };

        var content = SspService.GenerateSection5Content(null, system);

        content.Should().Be("System description fallback");
    }

    [Fact]
    public void Section5_NoSectionNoDescription_ReturnsPlaceholder()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov"
        };

        var content = SspService.GenerateSection5Content(null, system);

        content.Should().Contain("[Section not yet authored]");
    }

    [Fact]
    public void Section6_HybridMerge_IncludesBothParts()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Government"
        };
        var section = new SspSection
        {
            SectionNumber = 6, Content = "Physical security includes badge access and CCTV.",
            RegisteredSystemId = "sys-1", SectionTitle = "System Environment"
        };

        var content = SspService.GenerateSection6Content(system, section);

        content.Should().Contain("**Hosting Environment**: Azure Government");
        content.Should().Contain("### Environment Details");
        content.Should().Contain("Physical security includes badge access");
    }

    [Fact]
    public void Section6_NoAuthoredContent_ShowsPlaceholder()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Government"
        };

        var content = SspService.GenerateSection6Content(system, null);

        content.Should().Contain("**Hosting Environment**: Azure Government");
        content.Should().Contain("[Authored environment details not yet provided");
    }

    [Fact]
    public void Section7_InterconnectionsRepositioned_IncludesTable()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test System", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov"
        };
        var interconnections = new List<SystemInterconnection>
        {
            new()
            {
                Id = Guid.NewGuid().ToString(), RegisteredSystemId = "sys-1",
                TargetSystemName = "External HR", TargetSystemAcronym = "EHR",
                InterconnectionType = InterconnectionType.Direct,
                DataFlowDirection = DataFlowDirection.Bidirectional,
                DataClassification = "CUI", SecurityMeasures = new List<string> { "TLS 1.3", "VPN" },
                Status = InterconnectionStatus.Active,
                Agreements = new List<InterconnectionAgreement>
                {
                    new() { Status = AgreementStatus.Signed, Title = "ISA-001" }
                }
            }
        };

        var content = SspService.GenerateSection7Content(interconnections, system, null);

        content.Should().Contain("### Interconnection Summary");
        content.Should().Contain("1 interconnection(s)");
        content.Should().Contain("| External HR | EHR |");
        content.Should().Contain("Signed");
        content.Should().Contain("TLS 1.3, VPN");
        content.Should().Contain("### Information Sharing Policies");
    }

    [Fact]
    public void Section7_ManualOverride_ReturnsOverrideContent()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov"
        };
        var section = new SspSection
        {
            SectionNumber = 7, Content = "Custom interconnections narrative.",
            HasManualOverride = true, RegisteredSystemId = "sys-1",
            SectionTitle = "System Interconnections"
        };

        var content = SspService.GenerateSection7Content([], system, section);

        content.Should().Be("Custom interconnections narrative.");
    }

    [Fact]
    public void Section8_Authored_ReturnsContent()
    {
        var section = new SspSection
        {
            SectionNumber = 8, Content = "FISMA, HIPAA, and PCI-DSS apply.",
            RegisteredSystemId = "sys-1", SectionTitle = "Related Laws / Regulations"
        };

        var content = SspService.GenerateSection8Content(section);

        content.Should().Be("FISMA, HIPAA, and PCI-DSS apply.");
    }

    [Fact]
    public void Section8_NoContent_ReturnsPlaceholder()
    {
        var content = SspService.GenerateSection8Content(null);

        content.Should().Contain("[Section not yet authored]");
    }

    [Fact]
    public void Section9_IncludesTailoringRationale()
    {
        var baseline = new ControlBaseline
        {
            RegisteredSystemId = "sys-1", BaselineLevel = "Moderate",
            OverlayApplied = "FedRAMP Moderate",
            TotalControls = 325, CustomerControls = 200, InheritedControls = 100, SharedControls = 25,
            ControlIds = new List<string> { "AC-1", "AC-2" },
            Tailorings = new List<ControlTailoring>
            {
                new() { ControlId = "AC-99", Action = TailoringAction.Added,
                         Rationale = "Required by org policy", ControlBaselineId = "b1" },
                new() { ControlId = "MP-7", Action = TailoringAction.Removed,
                         Rationale = "No removable media permitted", ControlBaselineId = "b1" }
            }
        };
        var narratives = new List<ControlImplementation>
        {
            new() { ControlId = "AC-1", ImplementationStatus = ImplementationStatus.Implemented,
                     RegisteredSystemId = "sys-1" },
            new() { ControlId = "AC-2", ImplementationStatus = ImplementationStatus.Planned,
                     RegisteredSystemId = "sys-1" }
        };

        var content = SspService.GenerateSection9Content(baseline, narratives);

        content.Should().Contain("**Baseline Level**: Moderate");
        content.Should().Contain("**Overlay Applied**: FedRAMP Moderate");
        content.Should().Contain("### Tailored Controls");
        content.Should().Contain("AC-99: Required by org policy");
        content.Should().Contain("MP-7: No removable media permitted");
        content.Should().Contain("| Implemented | 1 |");
        content.Should().Contain("| Planned | 1 |");
        content.Should().Contain("§10 Control Implementations");
    }

    [Fact]
    public void Section9_NoBaseline_ReturnsPlaceholder()
    {
        var content = SspService.GenerateSection9Content(null, []);

        content.Should().Contain("not been selected");
    }

    [Fact]
    public void Section11_BoundaryResourceInventory()
    {
        var boundaryDefinitions = new List<AuthorizationBoundaryDefinition>
        {
            new() { Id = "bd-1", Name = "Primary", BoundaryType = BoundaryDefinitionType.Logical, IsPrimary = true, RegisteredSystemId = "sys-1", CreatedBy = "system" }
        };
        var boundaries = new List<AuthorizationBoundary>
        {
            new() { ResourceId = "/sub/rg/vm1", ResourceType = "Microsoft.Compute/virtualMachines",
                     ResourceName = "web-server-01", IsInBoundary = true,
                     InheritanceProvider = "CSP", RegisteredSystemId = "sys-1" },
            new() { ResourceId = "/sub/rg/nsg1", ResourceType = "Microsoft.Network/networkSecurityGroups",
                     ResourceName = "nsg-web", IsInBoundary = true,
                     RegisteredSystemId = "sys-1" },
            new() { ResourceId = "/sub/rg/sa-logs", ResourceType = "Microsoft.Storage/storageAccounts",
                     ResourceName = "sa-logs", IsInBoundary = false,
                     ExclusionRationale = "Shared logging, out of boundary",
                     RegisteredSystemId = "sys-1" }
        };
        var section = new SspSection
        {
            SectionNumber = 11, Content = "The boundary encompasses all Azure resources in RG-Web.",
            RegisteredSystemId = "sys-1", SectionTitle = "Authorization Boundary"
        };

        var content = SspService.GenerateSection11Content(boundaryDefinitions, boundaries, new List<InventoryItem>(), new List<SystemComponent>(), section);

        content.Should().Contain("### Boundary Description");
        content.Should().Contain("all Azure resources in RG-Web");
        content.Should().Contain("**Total Resources**: 3 (2 in-boundary, 1 excluded)");
        content.Should().Contain("| /sub/rg/vm1 | Microsoft.Compute/virtualMachines | web-server-01 | CSP |");
        content.Should().Contain("### Excluded Resources");
        content.Should().Contain("Shared logging, out of boundary");
    }

    [Fact]
    public void Section11_NoBoundaries_ReturnsPlaceholder()
    {
        var content = SspService.GenerateSection11Content(new List<AuthorizationBoundaryDefinition>(), [], new List<InventoryItem>(), new List<SystemComponent>(), null);

        content.Should().Contain("not been defined");
    }

    [Fact]
    public void Section12_PersonnelWithRolesAndAuthored()
    {
        var roles = new List<RmfRoleAssignment>
        {
            new() { RmfRole = RmfRole.Isso, UserId = "isso1", UserDisplayName = "Alice",
                     RegisteredSystemId = "sys-1", AssignedAt = DateTime.UtcNow, IsActive = true },
            new() { RmfRole = RmfRole.Issm, UserId = "issm1", UserDisplayName = "Bob",
                     RegisteredSystemId = "sys-1", AssignedAt = DateTime.UtcNow, IsActive = false }
        };
        var section = new SspSection
        {
            SectionNumber = 12, Content = "All personnel undergo background checks.",
            RegisteredSystemId = "sys-1", SectionTitle = "Personnel Security"
        };

        var content = SspService.GenerateSection12Content(roles, section);

        content.Should().Contain("| Isso | Alice | isso1 | Active |");
        content.Should().Contain("| Issm | Bob | issm1 | Inactive |");
        content.Should().Contain("### Screening, Access, and Training Requirements");
        content.Should().Contain("background checks");
    }

    [Fact]
    public void Section12_NoAuthored_ShowsPlaceholder()
    {
        var content = SspService.GenerateSection12Content([], null);

        content.Should().Contain("[Personnel security procedures not yet authored");
    }

    [Fact]
    public void Section13_ContingencyPlanMetadata()
    {
        var cp = new ContingencyPlanReference
        {
            RegisteredSystemId = "sys-1",
            DocumentTitle = "ISCP v3.0",
            DocumentLocation = "SharePoint/ISCP",
            DocumentVersion = "3.0",
            LastTestedDate = new DateTime(2024, 6, 15),
            TestType = "Tabletop Exercise",
            RecoveryTimeObjective = "4 hours",
            RecoveryPointObjective = "1 hour",
            AlternateProcessingSite = "Azure West US 2",
            BackupProceduresSummary = "Daily incremental, weekly full"
        };
        var section = new SspSection
        {
            SectionNumber = 13, Content = "The contingency plan is tested annually.",
            RegisteredSystemId = "sys-1", SectionTitle = "Contingency Plan"
        };

        var content = SspService.GenerateSection13Content(cp, section);

        content.Should().Contain("**Document Title**: ISCP v3.0");
        content.Should().Contain("**Last Tested**: 2024-06-15");
        content.Should().Contain("**Recovery Time Objective (RTO)**: 4 hours");
        content.Should().Contain("**Alternate Processing Site**: Azure West US 2");
        content.Should().Contain("### Contingency Plan Details");
        content.Should().Contain("tested annually");
    }

    [Fact]
    public void Section13_NoPlanNoSection_ReturnsPlaceholder()
    {
        var content = SspService.GenerateSection13Content(null, null);

        content.Should().Contain("[Contingency plan not yet documented");
    }

    [Fact]
    public void Section7_NoInterconnections_HasNoExternalFlag()
    {
        var system = new RegisteredSystem
        {
            Id = "sys-1", Name = "Test", SystemType = SystemType.MajorApplication,
            MissionCriticality = MissionCriticality.MissionEssential,
            HostingEnvironment = "Azure Gov", HasNoExternalInterconnections = true
        };

        var content = SspService.GenerateSection7Content([], system, null);

        content.Should().Contain("no external interconnections");
    }
}
