using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ato.Copilot.Core.Models.Tenancy.Attributes;

namespace Ato.Copilot.Core.Models.Compliance;

/// <summary>
/// Security Assessment Report (SAR) for a specific system assessment.
/// Follows a four-state lifecycle: NotStarted → Draft → UnderReview → Approved.
/// Contains auto-generated findings data plus editable narrative sections.
/// </summary>
[TenantScoped]
public class SecurityAssessmentReport
{
    /// <summary>
    /// FK to <see cref="Ato.Copilot.Core.Models.Tenancy.Tenant"/> — populated by
    /// <c>TenantStampingSaveChangesInterceptor</c> (Feature 048 FR-021).
    /// </summary>
    public Guid TenantId { get; set; }

    [Key]
    [MaxLength(36)]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [Required]
    [MaxLength(36)]
    public string RegisteredSystemId { get; set; } = string.Empty;

    [MaxLength(36)]
    public string? SapId { get; set; }

    [Required]
    [MaxLength(500)]
    public string Title { get; set; } = string.Empty;

    [Required]
    public SarStatus Status { get; set; } = SarStatus.NotStarted;

    public DateTime? AssessmentStartDate { get; set; }

    public DateTime? AssessmentEndDate { get; set; }

    public int TotalControlsAssessed { get; set; }

    public int TotalControlsPending { get; set; }

    public int SatisfiedCount { get; set; }

    public int NotSatisfiedCount { get; set; }

    /// <summary>JSON: {"catI": n, "catII": n, "catIII": n}</summary>
    [MaxLength(4000)]
    public string? FindingsBySeverity { get; set; }

    /// <summary>JSON: {"AC": n, "AU": n, ...}</summary>
    [MaxLength(8000)]
    public string? FindingsByFamily { get; set; }

    [Required]
    [MaxLength(200)]
    public string CreatedBy { get; set; } = string.Empty;

    [Required]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [MaxLength(200)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedAt { get; set; }

    [MaxLength(200)]
    public string? ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    [MaxLength(200)]
    public string? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    // Navigation properties
    [ForeignKey(nameof(RegisteredSystemId))]
    public RegisteredSystem? RegisteredSystem { get; set; }

    [ForeignKey(nameof(SapId))]
    public SecurityAssessmentPlan? SecurityAssessmentPlan { get; set; }

    public ICollection<SarSection> Sections { get; set; } = new List<SarSection>();
}

/// <summary>
/// Editable narrative section within a SAR.
/// Some sections are auto-generated from assessment data, others are user-authored.
/// </summary>
[TenantScoped]
public class SarSection
{
    /// <summary>
    /// FK to <see cref="Ato.Copilot.Core.Models.Tenancy.Tenant"/> — populated by
    /// <c>TenantStampingSaveChangesInterceptor</c> (Feature 048 FR-021).
    /// </summary>
    public Guid TenantId { get; set; }

    [Key]
    [MaxLength(36)]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [Required]
    [MaxLength(36)]
    public string SecurityAssessmentReportId { get; set; } = string.Empty;

    [Required]
    public SarSectionType SectionType { get; set; }

    [Required]
    [MaxLength(200)]
    public string Title { get; set; } = string.Empty;

    [MaxLength(32000)]
    public string? Content { get; set; }

    public bool IsAutoGenerated { get; set; }

    [MaxLength(200)]
    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedAt { get; set; }

    // Navigation
    [ForeignKey(nameof(SecurityAssessmentReportId))]
    public SecurityAssessmentReport? SecurityAssessmentReport { get; set; }
}
