using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Ato.Copilot.Core.Models.Tenancy.Attributes;

namespace Ato.Copilot.Core.Models.Compliance;

/// <summary>
/// Per-control implementation narrative for System Security Plan (SSP) authoring.
/// Stores the narrative text, implementation status, authorship, and AI-suggestion metadata.
/// </summary>
/// <remarks>
/// Feature 015 Phase 7 (US5). Unique constraint on (RegisteredSystemId, ControlId).
/// </remarks>
[TenantScoped]
public class ControlImplementation
{
    /// <summary>
    /// FK to <see cref="Ato.Copilot.Core.Models.Tenancy.Tenant"/> — populated by
    /// <c>TenantStampingSaveChangesInterceptor</c> (Feature 048 FR-021).
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>Unique identifier (GUID).</summary>
    [Key]
    [MaxLength(36)]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>FK to RegisteredSystem.</summary>
    [Required]
    [MaxLength(36)]
    public string RegisteredSystemId { get; set; } = string.Empty;

    /// <summary>NIST 800-53 control ID (e.g., "AC-1", "AC-2(12)").</summary>
    [Required]
    [MaxLength(20)]
    public string ControlId { get; set; } = string.Empty;

    /// <summary>Implementation status for this control.</summary>
    [Required]
    public ImplementationStatus ImplementationStatus { get; set; } = ImplementationStatus.Planned;

    /// <summary>Implementation narrative text for the SSP (up to 8000 chars).</summary>
    [MaxLength(8000)]
    public string? Narrative { get; set; }

    /// <summary>True if the narrative was auto-populated for an inherited control.</summary>
    public bool IsAutoPopulated { get; set; }

    /// <summary>True if the narrative was generated by AI suggestion.</summary>
    public bool AiSuggested { get; set; }

    /// <summary>User who reviewed/approved the narrative.</summary>
    [MaxLength(200)]
    public string? ReviewedBy { get; set; }

    /// <summary>When the narrative was reviewed (UTC).</summary>
    public DateTime? ReviewedAt { get; set; }

    /// <summary>User who authored the narrative.</summary>
    [Required]
    [MaxLength(200)]
    public string AuthoredBy { get; set; } = string.Empty;

    /// <summary>Authoring timestamp (UTC).</summary>
    public DateTime AuthoredAt { get; set; } = DateTime.UtcNow;

    /// <summary>Last modification timestamp (UTC).</summary>
    public DateTime? ModifiedAt { get; set; }

    // ─── Dashboard Capability Link (Feature 030) ──────────────────────────────

    /// <summary>FK to SecurityCapability that generated this narrative (null = manually authored).</summary>
    [MaxLength(36)]
    public string? SecurityCapabilityId { get; set; }

    /// <summary>True if user manually edited an auto-generated narrative (excluded from auto-update).</summary>
    public bool IsManuallyCustomized { get; set; }

    // ─── Governance (Feature 024) ────────────────────────────────────────────

    /// <summary>Approval lifecycle status for this narrative (Draft → UnderReview → Approved / NeedsRevision).</summary>
    public SspSectionStatus ApprovalStatus { get; set; } = SspSectionStatus.Draft;

    /// <summary>Current version number (monotonically increasing, 1-based).</summary>
    public int CurrentVersion { get; set; } = 1;

    /// <summary>FK to the most recently approved NarrativeVersion (null until first approval).</summary>
    [MaxLength(36)]
    public string? ApprovedVersionId { get; set; }

    // ─── Navigation ──────────────────────────────────────────────────────────

    /// <summary>Parent registered system.</summary>
    public RegisteredSystem RegisteredSystem { get; set; } = null!;

    /// <summary>Security capability that generated this narrative (null if manually authored).</summary>
    public SecurityCapability? SecurityCapability { get; set; }

    /// <summary>All version snapshots for this control implementation.</summary>
    public ICollection<NarrativeVersion> Versions { get; set; } = new List<NarrativeVersion>();

    /// <summary>The most recently approved version (null until first approval).</summary>
    public NarrativeVersion? ApprovedVersion { get; set; }
}

// ─── SSP DTOs ────────────────────────────────────────────────────────────────

/// <summary>
/// Result of a narrative suggestion by AI.
/// </summary>
public class NarrativeSuggestion
{
    /// <summary>Suggested narrative text.</summary>
    public string Narrative { get; set; } = string.Empty;

    /// <summary>Confidence score (0.0–1.0).</summary>
    public double Confidence { get; set; }

    /// <summary>Source references used for the suggestion.</summary>
    public List<string> References { get; set; } = new();

    /// <summary>Control ID the suggestion is for.</summary>
    public string ControlId { get; set; } = string.Empty;
}

/// <summary>
/// Result of batch narrative population for inherited controls.
/// </summary>
public class BatchPopulateResult
{
    /// <summary>Number of narratives populated.</summary>
    public int PopulatedCount { get; set; }

    /// <summary>Number of controls skipped (already had narratives).</summary>
    public int SkippedCount { get; set; }

    /// <summary>Control IDs that were populated.</summary>
    public List<string> PopulatedControlIds { get; set; } = new();

    /// <summary>Control IDs that were skipped.</summary>
    public List<string> SkippedControlIds { get; set; } = new();
}

/// <summary>
/// Per-family progress entry for narrative completion tracking.
/// </summary>
public class FamilyProgress
{
    /// <summary>Control family prefix (e.g., "AC", "AU").</summary>
    public string Family { get; set; } = string.Empty;

    /// <summary>Total controls in this family.</summary>
    public int Total { get; set; }

    /// <summary>Controls with completed narratives (Implemented status).</summary>
    public int Completed { get; set; }

    /// <summary>Controls with draft narratives (PartiallyImplemented or Planned with text).</summary>
    public int Draft { get; set; }

    /// <summary>Controls with no narrative text.</summary>
    public int Missing { get; set; }
}

/// <summary>
/// Overall narrative progress result for a system.
/// </summary>
public class NarrativeProgress
{
    /// <summary>System ID.</summary>
    public string SystemId { get; set; } = string.Empty;

    /// <summary>Total controls in the baseline.</summary>
    public int TotalControls { get; set; }

    /// <summary>Controls with completed narratives.</summary>
    public int CompletedNarratives { get; set; }

    /// <summary>Controls with draft narratives.</summary>
    public int DraftNarratives { get; set; }

    /// <summary>Controls with no narrative.</summary>
    public int MissingNarratives { get; set; }

    /// <summary>Overall completion percentage (0–100).</summary>
    public double OverallPercentage { get; set; }

    /// <summary>Per-family breakdown.</summary>
    public List<FamilyProgress> FamilyBreakdowns { get; set; } = new();
}

/// <summary>
/// Result of SSP document generation.
/// </summary>
public class SspDocument
{
    /// <summary>System ID.</summary>
    public string SystemId { get; set; } = string.Empty;

    /// <summary>System name.</summary>
    public string SystemName { get; set; } = string.Empty;

    /// <summary>Output format ("markdown" or "docx").</summary>
    public string Format { get; set; } = "markdown";

    /// <summary>Generated document content (Markdown).</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>Total controls included in the SSP.</summary>
    public int TotalControls { get; set; }

    /// <summary>Controls with narratives.</summary>
    public int ControlsWithNarratives { get; set; }

    /// <summary>Controls missing narratives (included as warnings).</summary>
    public int ControlsMissingNarratives { get; set; }

    /// <summary>Sections included in the document.</summary>
    public List<string> Sections { get; set; } = new();

    /// <summary>Generation timestamp.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Warning messages about missing or incomplete data.</summary>
    public List<string> Warnings { get; set; } = new();
}

// ─── SSP Section Management DTOs (Feature 022) ──────────────────────────────────

/// <summary>Completeness report for all 13 NIST 800-18 SSP sections.</summary>
public record SspCompletenessReport(
    string SystemName,
    double OverallReadinessPercent,
    int ApprovedCount,
    int TotalSections,
    List<SspSectionSummary> Sections,
    List<string> BlockingIssues);

/// <summary>Per-section summary within the completeness report.</summary>
public record SspSectionSummary(
    int SectionNumber,
    string SectionTitle,
    string Status,
    bool IsAutoGenerated,
    bool HasManualOverride,
    string? AuthoredBy,
    DateTime? AuthoredAt,
    int WordCount,
    int Version);
