using System.Diagnostics;
using System.Text.Json;
using Ato.Copilot.Agents.Common;
using Ato.Copilot.Core.Dtos.Dashboard;
using Ato.Copilot.Core.Interfaces.Compliance;
using Ato.Copilot.Core.Models.Compliance;
using Microsoft.Extensions.Logging;

namespace Ato.Copilot.Agents.Compliance.Tools;

// ═══════════════════════════════════════════════════════════════════════════════
// compliance_generate_sar
// ═══════════════════════════════════════════════════════════════════════════════

public class SarGenerateTool : BaseTool
{
    private readonly ISecurityAssessmentReportService _service;

    public SarGenerateTool(
        ISecurityAssessmentReportService service,
        ILogger<SarGenerateTool> logger) : base(logger)
    {
        _service = service;
    }

    public override string Name => "compliance_sar_generate";

    public override string Description =>
        "Generate a Security Assessment Report from existing assessment data. " +
        "Auto-populates findings sections and creates editable narrative sections. " +
        "RBAC: SCA, ISSM, or AO.";

    public override IReadOnlyDictionary<string, ToolParameter> Parameters => new Dictionary<string, ToolParameter>
    {
        ["system_id"] = new() { Name = "system_id", Description = "System GUID, name, or acronym", Type = "string", Required = true },
        ["title"] = new() { Name = "title", Description = "SAR document title", Type = "string", Required = true },
        ["sap_id"] = new() { Name = "sap_id", Description = "Optional governing SAP ID", Type = "string", Required = false }
    };

    public override async Task<string> ExecuteCoreAsync(
        Dictionary<string, object?> arguments,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        var systemId = GetArg<string>(arguments, "system_id");
        var title = GetArg<string>(arguments, "title");
        var sapId = GetArg<string>(arguments, "sap_id");

        if (string.IsNullOrWhiteSpace(systemId))
            return Error("INVALID_INPUT", "The 'system_id' parameter is required.");
        if (string.IsNullOrWhiteSpace(title))
            return Error("INVALID_INPUT", "The 'title' parameter is required.");

        try
        {
            var request = new CreateSarRequest { Title = title, SapId = sapId };
            var sar = await _service.CreateSarAsync(systemId, request, "mcp-user", cancellationToken);

            sw.Stop();
            return JsonSerializer.Serialize(new
            {
                status = "success",
                data = new
                {
                    sar_id = sar.Id,
                    system_id = sar.RegisteredSystemId,
                    title = sar.Title,
                    sar_status = sar.Status.ToString(),
                    total_controls_assessed = sar.TotalControlsAssessed,
                    satisfied_count = sar.SatisfiedCount,
                    not_satisfied_count = sar.NotSatisfiedCount,
                    sections = sar.Sections.Select(s => new
                    {
                        section_type = s.SectionType.ToString(),
                        title = s.Title,
                        is_auto_generated = s.IsAutoGenerated,
                        has_content = !string.IsNullOrWhiteSpace(s.Content)
                    }),
                    created_by = sar.CreatedBy,
                    created_at = sar.CreatedAt.ToString("O")
                },
                metadata = Meta(sw)
            }, JsonOpts);
        }
        catch (InvalidOperationException ex)
        {
            return Error("SAR_GENERATION_FAILED", ex.Message);
        }
    }

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, WriteIndented = true };

    private static string Error(string code, string message) =>
        JsonSerializer.Serialize(new { status = "error", errorCode = code, message }, new JsonSerializerOptions { WriteIndented = true });

    private object Meta(Stopwatch sw) => new { tool = Name, duration_ms = sw.ElapsedMilliseconds, timestamp = DateTime.UtcNow.ToString("O") };
}

// ═══════════════════════════════════════════════════════════════════════════════
// compliance_sar_edit_section
// ═══════════════════════════════════════════════════════════════════════════════

public class SarEditSectionTool : BaseTool
{
    private readonly ISecurityAssessmentReportService _service;

    public SarEditSectionTool(
        ISecurityAssessmentReportService service,
        ILogger<SarEditSectionTool> logger) : base(logger)
    {
        _service = service;
    }

    public override string Name => "compliance_sar_edit_section";

    public override string Description =>
        "Edit a narrative section of a Security Assessment Report. " +
        "Only works on editable sections (ExecutiveSummary, AssessmentScope, Recommendations) " +
        "when SAR is in NotStarted or Draft status. " +
        "RBAC: SCA, ISSM, or AO.";

    public override IReadOnlyDictionary<string, ToolParameter> Parameters => new Dictionary<string, ToolParameter>
    {
        ["sar_id"] = new() { Name = "sar_id", Description = "SAR ID (GUID)", Type = "string", Required = true },
        ["section_type"] = new() { Name = "section_type", Description = "Section type: ExecutiveSummary, AssessmentScope, Recommendations", Type = "string", Required = true },
        ["content"] = new() { Name = "content", Description = "New section content (Markdown)", Type = "string", Required = true }
    };

    public override async Task<string> ExecuteCoreAsync(
        Dictionary<string, object?> arguments,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        var sarId = GetArg<string>(arguments, "sar_id");
        var sectionTypeStr = GetArg<string>(arguments, "section_type");
        var content = GetArg<string>(arguments, "content");

        if (string.IsNullOrWhiteSpace(sarId))
            return Error("INVALID_INPUT", "The 'sar_id' parameter is required.");
        if (string.IsNullOrWhiteSpace(sectionTypeStr))
            return Error("INVALID_INPUT", "The 'section_type' parameter is required.");
        if (string.IsNullOrWhiteSpace(content))
            return Error("INVALID_INPUT", "The 'content' parameter is required.");

        if (!Enum.TryParse<SarSectionType>(sectionTypeStr, true, out var sectionType))
            return Error("INVALID_INPUT", $"Invalid section_type '{sectionTypeStr}'. Valid values: ExecutiveSummary, AssessmentScope, Recommendations.");

        try
        {
            var request = new EditSarSectionRequest { Content = content };
            var section = await _service.EditSectionAsync(sarId, sectionType, request, "mcp-user", cancellationToken);

            sw.Stop();
            return JsonSerializer.Serialize(new
            {
                status = "success",
                data = new
                {
                    section_type = section.SectionType.ToString(),
                    title = section.Title,
                    content_length = section.Content?.Length ?? 0,
                    modified_by = section.ModifiedBy,
                    modified_at = section.ModifiedAt?.ToString("O")
                },
                metadata = Meta(sw)
            }, JsonOpts);
        }
        catch (InvalidOperationException ex)
        {
            return Error("EDIT_FAILED", ex.Message);
        }
    }

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, WriteIndented = true };

    private static string Error(string code, string message) =>
        JsonSerializer.Serialize(new { status = "error", errorCode = code, message }, new JsonSerializerOptions { WriteIndented = true });

    private object Meta(Stopwatch sw) => new { tool = Name, duration_ms = sw.ElapsedMilliseconds, timestamp = DateTime.UtcNow.ToString("O") };
}

// ═══════════════════════════════════════════════════════════════════════════════
// compliance_sar_review
// ═══════════════════════════════════════════════════════════════════════════════

public class SarReviewTool : BaseTool
{
    private readonly ISecurityAssessmentReportService _service;

    public SarReviewTool(
        ISecurityAssessmentReportService service,
        ILogger<SarReviewTool> logger) : base(logger)
    {
        _service = service;
    }

    public override string Name => "compliance_sar_review";

    public override string Description =>
        "Submit a SAR for review, or approve/request revision. " +
        "Use action='submit' to transition Draft→UnderReview. " +
        "Use action='approve' or action='request_revision' to review. " +
        "RBAC: SCA/ISSM for submit, ISSM/AO for review.";

    public override IReadOnlyDictionary<string, ToolParameter> Parameters => new Dictionary<string, ToolParameter>
    {
        ["sar_id"] = new() { Name = "sar_id", Description = "SAR ID (GUID)", Type = "string", Required = true },
        ["action"] = new() { Name = "action", Description = "Action: submit, approve, request_revision", Type = "string", Required = true },
        ["comments"] = new() { Name = "comments", Description = "Optional reviewer comments (for approve/request_revision)", Type = "string", Required = false }
    };

    public override async Task<string> ExecuteCoreAsync(
        Dictionary<string, object?> arguments,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        var sarId = GetArg<string>(arguments, "sar_id");
        var action = GetArg<string>(arguments, "action");
        var comments = GetArg<string>(arguments, "comments");

        if (string.IsNullOrWhiteSpace(sarId))
            return Error("INVALID_INPUT", "The 'sar_id' parameter is required.");
        if (string.IsNullOrWhiteSpace(action))
            return Error("INVALID_INPUT", "The 'action' parameter is required.");

        try
        {
            SecurityAssessmentReport sar;

            switch (action.ToLowerInvariant())
            {
                case "submit":
                    sar = await _service.SubmitForReviewAsync(sarId, "mcp-user", cancellationToken);
                    break;
                case "approve":
                    sar = await _service.ReviewSarAsync(sarId, new ReviewSarRequest { Decision = "approve", Comments = comments }, "mcp-user", cancellationToken);
                    break;
                case "request_revision":
                    sar = await _service.ReviewSarAsync(sarId, new ReviewSarRequest { Decision = "request_revision", Comments = comments }, "mcp-user", cancellationToken);
                    break;
                default:
                    return Error("INVALID_INPUT", $"Invalid action '{action}'. Valid values: submit, approve, request_revision.");
            }

            sw.Stop();
            return JsonSerializer.Serialize(new
            {
                status = "success",
                data = new
                {
                    sar_id = sar.Id,
                    sar_status = sar.Status.ToString(),
                    modified_by = sar.ModifiedBy,
                    modified_at = sar.ModifiedAt?.ToString("O"),
                    message = action.ToLowerInvariant() switch
                    {
                        "submit" => "SAR submitted for review.",
                        "approve" => "SAR approved.",
                        "request_revision" => "Revision requested. SAR returned to Draft status.",
                        _ => "Action completed."
                    }
                },
                metadata = Meta(sw)
            }, JsonOpts);
        }
        catch (InvalidOperationException ex)
        {
            return Error("REVIEW_FAILED", ex.Message);
        }
    }

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, WriteIndented = true };

    private static string Error(string code, string message) =>
        JsonSerializer.Serialize(new { status = "error", errorCode = code, message }, new JsonSerializerOptions { WriteIndented = true });

    private object Meta(Stopwatch sw) => new { tool = Name, duration_ms = sw.ElapsedMilliseconds, timestamp = DateTime.UtcNow.ToString("O") };
}
